### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by jimy-byerley** [asny/tri-mesh#8] opened 2019-09-13 16:20 UTC
Hi ! 
2 month ago, I started a project like yours on my own. The goal was to begin a mesh-oriented CAD software. I wrote the intersection functions and some mesh simplification tools ... 
and now I found `tri-mesh` !

I'm seeking at switching to your library (and get involved) or to keep mine.
So I have some questions about this library.

- are the intersection functions reliable ? (I mean, returning a good result absolutely everytime)
- is the mesh data access fast ? (I see you are storing the mesh's points into a hashmap. I hesitated to do this for my own, but finally I decided to do not cause I thought it would be realy slower).
- is the data structure memory-efficient ? (in comparison with a simple [vec3] slice)

**Comment by asny** [comment] 2019-09-14 18:05
Hi.
That sounds like an interesting and challenging project you have started! A CAD software targeting a specific industry or a general tool, if I might ask?
You are more than welcome to use tri-mesh and any contributions will be highly appreciated. I started this project at my previous workplace where I was working full time on this and other projects. Now, I don't have the same time to dedicate to tri-mesh but it has been my plan all along to continue developing once in a while and I will for sure be available if you have questions or requests. If you want to contribute, this is very simple since there is one central data structure (the mesh) and all other functionality is operations on that mesh. So if you need some functionality, just add that (maybe using some other functionality, like iterators or traversal) and it will be independent of everything else. 

And now for the questions:
> * are the intersection functions reliable ? (I mean, returning a good result absolutely everytime)
All functionality is thoroughly unit tested so I think it is very reliable, but of course there is no guarantee that there are not a bug hiding somewhere. Also the intersection functions take all cases into account except one case in face_line_piece_intersection which is described in a todo there. 

> * is the mesh data access fast ? (I see you are storing the mesh's points into a hashmap. I hesitated to do this for my own, but finally I decided to do not cause I thought it would be realy slower).
Well, I had the same considerations and a flat array will probably be faster, but I don't know how much you will gain. Anyway I think it is really fast as it is and it makes everything much easier to use a hashmap when you want to add and remove vertices. So my strategy is always to make the code as simple as possible at first and then optimise where necessary, so if someone at some point finds out that hashmap is not fast enough for some purpose, then we can for sure change to flat arrays.

> * is the data structure memory-efficient ? (in comparison with a simple [vec3] slice)
To be able to do efficient operations on the mesh, you have to have the connectivity information available. That means you will use more memory than just storing indices and positions (you can convert the mesh data structure to an efficient indices+position buffers using the export functionality), but it is still quite memory efficient. For each vertex I store 3 ints and 3 floats (the position), for each face I store 2 ints and for each halfedge I store 5 ints. I could probably save one or two ints, but not much more if I want efficient traversal of the mesh.

Hope that answers your questions, otherwise, please just ask again.
- Asger.

**Comment by jimy-byerley** [comment] 2019-09-17 13:03
Thank you for all these details !

My project is more like a general purpose CAD, but not buid on the same idea as the other software I know. I work on it on my free time, I don't know yet if I will opensource it (i would like to, but I have to consider the option of a startup)

I will try to quickly benchmark my algorithm and yours in the next weeks.

**Comment by jimy-byerley** [comment] 2019-10-23 16:06
So to sum-up:
- I were not able to perform tests on complex meshes because of a remaining bug in my algorithm.
- On small meshes, tri-mesh is 20 times slower than my algorithm and (I don't know how much) quite slower than blender's for the same meshes (I testes cubes, cylinder and blender's suzanne).

I try to figure why there is this huge overhead of time computations with tri-mesh. It may be because of the hashmap access time, but it seems huge for a hashmap using `usize` as key type. 
It can be also the need to follow 3 halfedges to find the next edge for each iteration around a point, but I'm not convinced.
Maybe It's because you split and merge meshes a sort of edition mode (I mean you insert halfedges one by one in an existing mesh) and so that can induce many copy operation for elements insertion.

Now that I know more about halfedges, I think that I would rewrite my algorithm with it, so my library would not be so different than yours in definitely. I think it is better to use yours and see if it's possible to boost performances.

Have you any idea for what we can try to speed up the mesh split operation ?

**Comment by asny** [comment] 2019-10-26 09:54
First of all, thanks a lot for testing and I really appreciate your effort!

> * On small meshes, tri-mesh is 20 times slower than my algorithm for the same meshes and (I don't know how much) quite slower than blender's (I testes cubes, cylinder and blender's suzanne).

20 times slower seems like a lot, but not at all impossible (I still have to ask if you forgot a --release? I do that sometimes). I have been optimising some parts, but not everything and especially not splitting which I have only used where necessary. This means that I have not optimised a case like subdivision where there are a lot of splitting of faces or edges. As you point out, I do splitting of for example faces one by one which is of course slower than splitting all faces at once. The reason is that splitting all faces is something you want to do one time and offline and therefore not as performance critical as realtime editing as in the morph example. But maybe that is critical in your case? Anyway, I would like to help optimising, but I might need to know a bit more about what exactly you are interested in. Maybe you can specify a simple test case, which is not your algorithm but uses the same operations?

Anyway, I will take a look at the split operations and see if I can optimise them. I have also given some thoughts into whether using hashmaps is a good approach, not because of the map itself, but because all keys have to be hashed, which is a total waste of time when the keys are unique integers anyway. Probably just changing the hashing function would make a huge speed-up, so I will try to do that or switch to plain arrays and add more bookkeeping to reuse the memory of deleted primitives. It will take some time though, I have very little time at the moment.

> Now that I know more about halfedges, I think that I would rewrite my algorithm with it, so my library would not be so different than yours in definitely ;). I think it is better to use yours and see if it's possible to boost performances.

I am glad that you have learned something. If you need to traverse the mesh a lot or apply complex operations then the half-edge data structure is probably an optimal choice between memory efficiency and performance. I have to mention though that it is also a bit hated by some, I am not exactly sure why, but of course it does not work well for everything. For example if you just want to do subdivisions then this data structure is overkill and just complicates things and actually makes it less performant.

**Comment by asny** [comment] 2019-10-27 20:28
A quick update. I tried making a custom hashing function which simply outputs the same value as the input. This, together with making all IDs 32 bit integers instead of 64 bit, gave me a 6-7 times speed-up on a simple test-case. If you want to test again, I have merged the changes into master, but not released a new version of the crate.

Also, I want to change to arrays instead of hashmap but that is going to take a bit more time.

**Comment by jimy-byerley** [comment] 2019-10-28 09:36
> (I still have to ask if you forgot a --release? I do that sometimes).

Unfortunately yes, without the --release option, the speed ratio is even bigger.

> not because of the map itself, but because all keys have to be hashed, which is a total waste of time when the keys are unique integers anyway. 

That's a point I didn't consider ! I thought hash(n) was n for any integer. Sure it can accelerate to make it so if it's not already the case.

> Maybe you can specify a simple test case, which is not your algorithm but uses the same operations?

Sure ! I'll send you my test by mail. My boolean functions are implemented in `madcad-rs/src/intersection.rs`, the rest is for other functions that doesn't really matter and definitions that matter but are quite obvious. The folder `madcad-vs-trimesh` is for the test and juste compare the speed at intersecting the mesh `untitled.obj` (which is currenty the blender's suzanne)


**To be more precise on my project:**
What I need for my project is in fact just basic operations to create object envelopes:
- boolean operations
- smooth ability
- mesh join
- normal computations (surely faster with halfedge because of the necessity to propagate)
- extrusions, revolutions, etc  (but these are very simple to write)

My CAD program would be mesh-based, so every single operation would be mesh boolean operations. As it's usefull (and it's the main goal of a CAD tool), the entire mesh is regenerated each time the user changes a parameter at start of it's construction tree. Therefore I need the regeneration and thus the boolean operation to be as fast as possible.

**Comment by jimy-byerley** [comment] 2019-10-31 17:22
By the way, I want to add somme generation functions, like extrusion, revolution, etc
This kind of function is natively using meshes described by set of faces. So there is two approach:
- write these functions using face buffers, then build a halfedge mesh
- write these functions creating faces using trimesh::mesh::create_face
What according to you is the better ?

**Comment by asny** [comment] 2019-11-05 19:07
So first of all, I have been optimising quite a bit and no matter which operation you apply it should be much much faster now. If your test is working again, can you please run it again using `tri-mesh = {git = “https://github.com/asny/tri-mesh”}` or send it to me again? I am kind og curious whether this solved (most of) the problem! :)

> By the way, I want to add somme generation functions, like extrusion, revolution, etc
> This kind of function is natively using meshes described by set of faces. So there is two approach:
> 
> write these functions using face buffers, then build a halfedge mesh
> write these functions creating faces using trimesh::mesh::create_face
> What according to you is the better ?

To answer your question, I want to broaden it a bit and come back to it at the end. 

Meshes are not well suited for everything and the half edge data structure is suited for even less. Therefore, using an optimal data structure for the purpose at hand and then converting to another data structure when necessary will probably save you development time as well as increase performance in some cases and in others it will not. I’m not sure what will be most optimal in each case, but I have some general observations. 

* Triangle meshes are very difficult to use for boolean operations and mesh join. So why did I choose to implement it? Well, I had a triangle mesh as input and wanted to preserve that input mesh while stitching it together with other meshes. If you are not that concerned about changes to the input meshes, then SDFs are much easier to use for boolean operations. Maybe it is not that big a concern since you already have that functionality implemented, but you still need to address the cases where the boolean operations produce garbage geometry where there are a lot of intersections within a small volume. And as you say, you use boolean operations a lot, so you will probably run into these cases a lot!

* Smoothing and normal computations are easy to do on a triangle mesh (you probably know this, it is just for the record).

* Extrusion, revolutions etc is somewhere in between. If you want to create a complete new mesh with for example an extrusion, then I would create face buffers and then build a half edge mesh from that. This is the easiest and probably the fastest. If you already have a half edge mesh and want to extrude from that, then you can use split face and split edge and move the vertices to get the geometry you want. This allows for quite complex geometry to grow dynamically. Also remember to flip edges and other quality improvements once in a while to maintain nice geometry. The problem with using create_face is that it will not connect the face with the rest of the mesh unless you merge (which is expensive). And if you don’t have the connectivity between faces, there is no point in using a half edge datastructure.

**Comment by jimy-byerley** [comment] 2019-11-10 13:48
> If your test is working again, can you please run it again using tri-mesh = {git = “https://github.com/asny/tri-mesh”} or send it to me again? I am kind og curious whether this solved (most of) the problem! :)

I can't make it work again :-/ I think I had modified something since the first time so it doesn't work anymore, and as I didn't versioned my code would have a hard time at solving this. I think it would be a waste of time to do so.
But I tested tri-mesh with the same code as before but with your last modifications and I must say that it's 10x faster !  I have no more doubts now !

BTW: I suggested a [small improvement](https://github.com/asny/tri-mesh/pull/10) for the mesh build method

**Comment by asny** [comment] 2019-11-15 07:33
Perfectly all right, all I want to know is whether it is fast enough :) I will look into the pull request as soon as possible, hopefully in the weekend.

**Closed** 2019-11-26 19:09 UTC
